/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/orchestration/airflow/service/v1/environments.proto

package com.google.cloud.orchestration.airflow.service.v1;

public final class EnvironmentsOuterClass {
  private EnvironmentsOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_CreateEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_CreateEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_GetEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_GetEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_DeleteEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_DeleteEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_UpdateEnvironmentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_UpdateEnvironmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_EnvironmentConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_EnvironmentConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_AllowedIpRange_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_AllowedIpRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_DatabaseConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_DatabaseConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_WebServerConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_EncryptionConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_EncryptionConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_AirflowConfigOverridesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_AirflowConfigOverridesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_PypiPackagesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_PypiPackagesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_EnvVariablesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_EnvVariablesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_IPAllocationPolicy_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_IPAllocationPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_NodeConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_NodeConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_PrivateClusterConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_PrivateClusterConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_PrivateEnvironmentConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_PrivateEnvironmentConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_Environment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_Environment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_Environment_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_Environment_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_PypiDependenciesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_PypiDependenciesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "@google/cloud/orchestration/airflow/service/v1/environments.proto\022-google.cloud"
          + ".orchestration.airflow.service.v1\032\034googl"
          + "e/api/annotations.proto\032\027google/api/clie"
          + "nt.proto\032\037google/api/field_behavior.prot"
          + "o\032\031google/api/resource.proto\032#google/longrunning/operations.proto\032"
          + " google/protobuf/field_mask.proto\032\037google/protobuf/timestamp.proto\"{\n"
          + "\030CreateEnvironmentRequest\022\016\n"
          + "\006parent\030\001 \001(\t\022O\n"
          + "\013environment\030\002"
          + " \001(\0132:.google.cloud.orchestration.airflow.service.v1.Environment\"%\n"
          + "\025GetEnvironmentRequest\022\014\n"
          + "\004name\030\001 \001(\t\"P\n"
          + "\027ListEnvironmentsRequest\022\016\n"
          + "\006parent\030\001 \001(\t\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\"\205\001\n"
          + "\030ListEnvironmentsResponse\022P\n"
          + "\014environments\030\001"
          + " \003(\0132:.google.cloud.orchestration.airflow.service.v1.Environment\022\027\n"
          + "\017next_page_token\030\002 \001(\t\"(\n"
          + "\030DeleteEnvironmentRequest\022\014\n"
          + "\004name\030\001 \001(\t\"\252\001\n"
          + "\030UpdateEnvironmentRequest\022\014\n"
          + "\004name\030\002 \001(\t\022O\n"
          + "\013environment\030\001"
          + " \001(\0132:.google.cloud.orchestration.airflow.service.v1.Environment\022/\n"
          + "\013update_mask\030\003 \001(\0132\032.google.protobuf.FieldMask\"\232\006\n"
          + "\021EnvironmentConfig\022\023\n"
          + "\013gke_cluster\030\001 \001(\t\022\026\n"
          + "\016dag_gcs_prefix\030\002 \001(\t\022\022\n\n"
          + "node_count\030\003 \001(\005\022V\n"
          + "\017software_config\030\004"
          + " \001(\0132=.google.cloud.orchestration.airflow.service.v1.SoftwareConfig\022N\n"
          + "\013node_config\030\005"
          + " \001(\01329.google.cloud.orchestration.airflow.service.v1.NodeConfig\022k\n"
          + "\032private_environment_config\030\007"
          + " \001(\0132G.google.cloud.orchestration.airflow.service.v1.PrivateEnvironmentConfig\022|\n"
          + "!web_server_network_access_control\030\010"
          + " \001(\0132L.google.cloud.orchestration.airflow.service.v1.WebServerNetworkAccessControlB\003\340A\001\022[\n"
          + "\017database_config\030\t"
          + " \001(\0132=.google.cloud.orchestration.airflow.service.v1.DatabaseConfigB\003\340A\001\022^\n"
          + "\021web_server_config\030\n"
          + " \001(\0132>.google.cloud.orchestration.airflow.service.v1.WebServerConfigB\003\340A\001\022_\n"
          + "\021encryption_config\030\013"
          + " \001(\0132?.google.cloud.orchestration.airflow.service.v1.EncryptionConfigB\003\340A\001\022\023\n"
          + "\013airflow_uri\030\006 \001(\t\"\322\001\n"
          + "\035WebServerNetworkAccessControl\022v\n"
          + "\021allowed_ip_ranges\030\001"
          + " \003(\0132[.google.cloud.orchestration.airflow.service.v1.WebServerNetworkAccessControl.AllowedIpRange\0329\n"
          + "\016AllowedIpRange\022\r\n"
          + "\005value\030\001 \001(\t\022\030\n"
          + "\013description\030\002 \001(\tB\003\340A\001\"+\n"
          + "\016DatabaseConfig\022\031\n"
          + "\014machine_type\030\001 \001(\tB\003\340A\001\",\n"
          + "\017WebServerConfig\022\031\n"
          + "\014machine_type\030\001 \001(\tB\003\340A\001\"-\n"
          + "\020EncryptionConfig\022\031\n"
          + "\014kms_key_name\030\001 \001(\tB\003\340A\001\"\265\004\n"
          + "\016SoftwareConfig\022\025\n\r"
          + "image_version\030\001 \001(\t\022{\n"
          + "\030airflow_config_overrides\030\002"
          + " \003(\0132Y.google.cloud.orchestration.airflow.service.v1.SoftwareConfig.AirflowConfigOverridesEntry\022f\n\r"
          + "pypi_packages\030\003"
          + " \003(\0132O.google.cloud.orchestration.airflow.service.v1.SoftwareConfig.PypiPackagesEntry\022f\n\r"
          + "env_variables\030\004"
          + " \003(\0132O.google.cloud.orchestration.airflow.service.v1.SoftwareConfig.EnvVariablesEntry\022\026\n"
          + "\016python_version\030\006 \001(\t\032=\n"
          + "\033AirflowConfigOverridesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\0323\n"
          + "\021PypiPackagesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\0323\n"
          + "\021EnvVariablesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\220\002\n"
          + "\022IPAllocationPolicy\022\033\n"
          + "\016use_ip_aliases\030\001 \001(\010B\003\340A\001\022+\n"
          + "\034cluster_secondary_range_name\030\002 \001(\tB\003\340A\001H\000\022&\n"
          + "\027cluster_ipv4_cidr_block\030\004 \001(\tB\003\340A\001H\000\022,\n"
          + "\035services_secondary_range_name\030\003 \001(\tB\003\340A\001H\001\022\'\n"
          + "\030services_ipv4_cidr_block\030\005 \001(\tB\003\340A\001H\001B\027\n"
          + "\025cluster_ip_allocationB\030\n"
          + "\026services_ip_allocation\"\222\002\n\n"
          + "NodeConfig\022\020\n"
          + "\010location\030\001 \001(\t\022\024\n"
          + "\014machine_type\030\002 \001(\t\022\017\n"
          + "\007network\030\003 \001(\t\022\022\n\n"
          + "subnetwork\030\004 \001(\t\022\024\n"
          + "\014disk_size_gb\030\005 \001(\005\022\024\n"
          + "\014oauth_scopes\030\006 \003(\t\022\027\n"
          + "\017service_account\030\007 \001(\t\022\014\n"
          + "\004tags\030\010 \003(\t\022d\n"
          + "\024ip_allocation_policy\030\t"
          + " \001(\0132A.google.cloud.orchestration.airflow.service.v1.IPAllocationPolicyB\003\340A\001\"\212\001\n"
          + "\024PrivateClusterConfig\022$\n"
          + "\027enable_private_endpoint\030\001 \001(\010B\003\340A\001\022#\n"
          + "\026master_ipv4_cidr_block\030\002 \001(\tB\003\340A\001\022\'\n"
          + "\032master_ipv4_reserved_range\030\003 \001(\tB\003\340A\003\"\253\002\n"
          + "\030PrivateEnvironmentConfig\022\'\n"
          + "\032enable_private_environment\030\001 \001(\010B\003\340A\001\022h\n"
          + "\026private_cluster_config\030\002"
          + " \001(\0132C.google.cloud.orchestration.airflow.service.v1.PrivateClusterConfigB\003\340A\001\022\'\n"
          + "\032web_server_ipv4_cidr_block\030\003 \001(\tB\003\340A\001\022&\n"
          + "\031cloud_sql_ipv4_cidr_block\030\004 \001(\tB\003\340A\001\022+\n"
          + "\036web_server_ipv4_reserved_range\030\005 \001(\tB\003\340A\003\"\205\005\n"
          + "\013Environment\022\014\n"
          + "\004name\030\001 \001(\t\022P\n"
          + "\006config\030\002"
          + " \001(\0132@.google.cloud.orchestration.airflow.service.v1.EnvironmentConfig\022\014\n"
          + "\004uuid\030\003 \001(\t\022O\n"
          + "\005state\030\004"
          + " \001(\0162@.google.cloud.orchestration.airflow.service.v1.Environment.State\022/\n"
          + "\013create_time\030\005 \001(\0132\032.google.protobuf.Timestamp\022/\n"
          + "\013update_time\030\006 \001(\0132\032.google.protobuf.Timestamp\022V\n"
          + "\006labels\030\007"
          + " \003(\0132F.google.cloud.orchestration.airflow.service.v1.Environment.LabelsEntry\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"`\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\014\n"
          + "\010CREATING\020\001\022\013\n"
          + "\007RUNNING\020\002\022\014\n"
          + "\010UPDATING\020\003\022\014\n"
          + "\010DELETING\020\004\022\t\n"
          + "\005ERROR\020\005:l\352Ai\n"
          + "#composer.googleapis.com/Environment\022Bprojects/{project}/locations/{location}/environments/{environment}\"\371\003\n"
          + "\024CheckUpgradeResponse\022\032\n\r"
          + "build_log_uri\030\001 \001(\tB\003\340A\003\022\177\n"
          + "\036contains_pypi_modules_conflict\030\004"
          + " \001(\0162R.google.cloud.orchestration.airflow.service.v1.CheckUpgradeResponse.ConflictResultB\003\340A\003\022,\n"
          + "\037pypi_conflict_build_log_extract\030\003 \001(\tB\003\340A\003\022\025\n\r"
          + "image_version\030\005 \001(\t\022t\n"
          + "\021pypi_dependencies\030\006"
          + " \003(\0132Y.google.cloud.orchestration.airflow.service.v1.CheckUpgradeResponse.PypiDependenciesEntry\0327\n"
          + "\025PypiDependenciesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"P\n"
          + "\016ConflictResult\022\037\n"
          + "\033CONFLICT_RESULT_UNSPECIFIED\020\000\022\014\n"
          + "\010CONFLICT\020\001\022\017\n"
          + "\013NO_CONFLICT\020\0022\227\013\n"
          + "\014Environments\022\251\002\n"
          + "\021CreateEnvironment\022G.google.cloud.orchestration.airflow.service"
          + ".v1.CreateEnvironmentRequest\032\035.google.longrunning.Operation\"\253\001\202\323\344\223\002?\"0/v1/{parent=projects/*/locations/*}/environments:\013environment\332A\022parent,environment\312AN\n"
          + "\013Environment\022?google.cloud.orchestration.airflow.service.v1.OperationMetadata\022\323\001\n"
          + "\016GetEnvironment\022D.google.cloud.orchestratio"
          + "n.airflow.service.v1.GetEnvironmentRequest\032:.google.cloud.orchestration.airflow.service.v1.Environment\"?\202\323\344\223\0022\0220/v1/{name=projects/*/locations/*/environments/*}\332A\004name\022\346\001\n"
          + "\020ListEnvironments\022F.google.cloud.orchestration.airflow.service.v1.Lis"
          + "tEnvironmentsRequest\032G.google.cloud.orchestration.airflow.service.v1.ListEnvironmentsResponse\"A\202\323\344\223\0022\0220/v1/{parent=projects/*/locations/*}/environments\332A\006parent\022\263\002\n"
          + "\021UpdateEnvironment\022G.google.cloud.orchestration.airflow.service.v1.UpdateEnv"
          + "ironmentRequest\032\035.google.longrunning.Operation\"\265\001\202\323\344\223\002?20/v1/{name=projects/*/locations/*/environments/*}:\013environment\332A\034name,environment,update_mask\312AN\n"
          + "\013Environment\022?google.cloud.orchestration.airflow.service.v1.OperationMetadata\022\230\002\n"
          + "\021DeleteEnvironment\022G.google.cloud.orchestratio"
          + "n.airflow.service.v1.DeleteEnvironmentRequest\032\035.google.longrunning.Operation\"\232\001\202\323\344\223\0022*0/v1/{name=projects/*/locations/*/environments/*}\332A\004name\312AX\n"
          + "\025google.protobuf.Empty\022?google.cloud.orchestration.airflow.service.v1.OperationMetadata\032K\312A\027composer.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\213\001\n"
          + "1com.google.cloud.orchestration.airflow.servic"
          + "e.v1P\001ZTgoogle.golang.org/genproto/googleapis/cloud/orchestration/airflow/servic"
          + "e/v1;serviceb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_CreateEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_orchestration_airflow_service_v1_CreateEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_CreateEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Environment",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_GetEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_orchestration_airflow_service_v1_GetEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_GetEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_ListEnvironmentsResponse_descriptor,
            new java.lang.String[] {
              "Environments", "NextPageToken",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_DeleteEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_orchestration_airflow_service_v1_DeleteEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_DeleteEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_UpdateEnvironmentRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_orchestration_airflow_service_v1_UpdateEnvironmentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_UpdateEnvironmentRequest_descriptor,
            new java.lang.String[] {
              "Name", "Environment", "UpdateMask",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_EnvironmentConfig_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_orchestration_airflow_service_v1_EnvironmentConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_EnvironmentConfig_descriptor,
            new java.lang.String[] {
              "GkeCluster",
              "DagGcsPrefix",
              "NodeCount",
              "SoftwareConfig",
              "NodeConfig",
              "PrivateEnvironmentConfig",
              "WebServerNetworkAccessControl",
              "DatabaseConfig",
              "WebServerConfig",
              "EncryptionConfig",
              "AirflowUri",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_descriptor,
            new java.lang.String[] {
              "AllowedIpRanges",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_AllowedIpRange_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_AllowedIpRange_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_WebServerNetworkAccessControl_AllowedIpRange_descriptor,
            new java.lang.String[] {
              "Value", "Description",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_DatabaseConfig_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_orchestration_airflow_service_v1_DatabaseConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_DatabaseConfig_descriptor,
            new java.lang.String[] {
              "MachineType",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerConfig_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_orchestration_airflow_service_v1_WebServerConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_WebServerConfig_descriptor,
            new java.lang.String[] {
              "MachineType",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_EncryptionConfig_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_orchestration_airflow_service_v1_EncryptionConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_EncryptionConfig_descriptor,
            new java.lang.String[] {
              "KmsKeyName",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor,
            new java.lang.String[] {
              "ImageVersion",
              "AirflowConfigOverrides",
              "PypiPackages",
              "EnvVariables",
              "PythonVersion",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_AirflowConfigOverridesEntry_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_AirflowConfigOverridesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_AirflowConfigOverridesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_PypiPackagesEntry_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_PypiPackagesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_PypiPackagesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_EnvVariablesEntry_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_EnvVariablesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_SoftwareConfig_EnvVariablesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_IPAllocationPolicy_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_orchestration_airflow_service_v1_IPAllocationPolicy_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_IPAllocationPolicy_descriptor,
            new java.lang.String[] {
              "UseIpAliases",
              "ClusterSecondaryRangeName",
              "ClusterIpv4CidrBlock",
              "ServicesSecondaryRangeName",
              "ServicesIpv4CidrBlock",
              "ClusterIpAllocation",
              "ServicesIpAllocation",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_NodeConfig_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_orchestration_airflow_service_v1_NodeConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_NodeConfig_descriptor,
            new java.lang.String[] {
              "Location",
              "MachineType",
              "Network",
              "Subnetwork",
              "DiskSizeGb",
              "OauthScopes",
              "ServiceAccount",
              "Tags",
              "IpAllocationPolicy",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_PrivateClusterConfig_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_orchestration_airflow_service_v1_PrivateClusterConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_PrivateClusterConfig_descriptor,
            new java.lang.String[] {
              "EnablePrivateEndpoint", "MasterIpv4CidrBlock", "MasterIpv4ReservedRange",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_PrivateEnvironmentConfig_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_orchestration_airflow_service_v1_PrivateEnvironmentConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_PrivateEnvironmentConfig_descriptor,
            new java.lang.String[] {
              "EnablePrivateEnvironment",
              "PrivateClusterConfig",
              "WebServerIpv4CidrBlock",
              "CloudSqlIpv4CidrBlock",
              "WebServerIpv4ReservedRange",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_Environment_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_orchestration_airflow_service_v1_Environment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_Environment_descriptor,
            new java.lang.String[] {
              "Name", "Config", "Uuid", "State", "CreateTime", "UpdateTime", "Labels",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_Environment_LabelsEntry_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_Environment_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_orchestration_airflow_service_v1_Environment_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_Environment_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_descriptor,
            new java.lang.String[] {
              "BuildLogUri",
              "ContainsPypiModulesConflict",
              "PypiConflictBuildLogExtract",
              "ImageVersion",
              "PypiDependencies",
            });
    internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_PypiDependenciesEntry_descriptor =
        internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_PypiDependenciesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_orchestration_airflow_service_v1_CheckUpgradeResponse_PypiDependenciesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
